


spring:

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  config:
    activate:
      on-profile: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: wnsghks4104@gmail.com
    password: [비밀번호]
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://[Rds endPoint]/[DB name]?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull&connectTimeout=60
    username: [아이디]
    password: [비밀번호]

  devtools:
    livereload:
      enabled: true

    freemarker:
      cache: false

    thymeleaf:
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      open-in-view: true

  thymeleaf:
    prefix: classpath:/templates/